# Generated by Django 3.2 on 2021-12-24 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autors', '0002_rename_author_autors_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autors',
            name='autor',
        ),
        migrations.AddField(
            model_name='autors',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
