# Generated by Django 3.2 on 2021-12-24 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drafts', '0002_auto_20211224_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drafts',
            new_name='DraftsModel',
        ),
        migrations.AlterModelOptions(
            name='draftsmodel',
            options={'verbose_name': 'Draft', 'verbose_name_plural': 'Drafts'},
        ),
    ]
