# Generated by Django 3.2 on 2021-12-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0005_alter_draftsmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftsmodel',
            old_name='user_draft',
            new_name='user',
        ),
    ]
