# Generated by Django 3.2 on 2021-12-27 11:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0007_rename_image_draftsmodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsmodel',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
