# Generated by Django 3.2 on 2021-12-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0008_draftsmodel_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftsmodel',
            name='images',
        ),
    ]
