# Generated by Django 3.2 on 2021-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0009_remove_draftsmodel_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsmodel',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
