# Generated by Django 3.2 on 2021-12-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafts', '0010_draftsmodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftsmodel',
            name='content',
        ),
    ]
